Fixed compilation issues with GLUT on linux
This fixes the missing glut library while linking plycmd, plyv
on fedora f35

[ 96%] Linking CXX executable plycmd
/usr/bin/ld: ../gvr/libgvr_static.a(glmisc.cc.o): in function `gvr::renderInfoText(char const*, long, long)':
glmisc.cc:(.text+0x146): undefined reference to `glutBitmap9By15'
/usr/bin/ld: glmisc.cc:(.text+0x15b): undefined reference to `glutBitmapWidth'
/usr/bin/ld: glmisc.cc:(.text+0x31c): undefined reference to `glutBitmap9By15'
/usr/bin/ld: glmisc.cc:(.text+0x333): undefined reference to `glutBitmapCharacter'
/usr/bin/ld: ../gvr/libgvr_static.a(glmisc.cc.o): in function `gvr::renderInfoLine(char const*, long)':
glmisc.cc:(.text+0x500): undefined reference to `glutBitmap9By15'
/usr/bin/ld: glmisc.cc:(.text+0x510): undefined reference to `glutBitmapCharacter'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/CMakeFiles/plycmd.dir/build.make:111: tools/plycmd] Error 1
make[1]: *** [CMakeFiles/Makefile2:561: tools/CMakeFiles/plycmd.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

Signed-off-by: Xavier Roumegue <xavier.roumegue@nxp.com>